Repository googleapis/nodejs-speech, pull requests merged in 2018-03, with the labels that each got.

#39 Upgrade repo-tools and regenerate scaffolding.
  .github/ISSUE_TEMPLATE.md
  .gitignore
  CONTRIBUTORS
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/package-lock.json
Labels: cla: yes

#41 v1.2.0
  package-lock.json
  package.json
  samples/package-lock.json
Labels: cla: yes

#42 chore: setup nighty build in CircleCI
  .circleci/config.yml
  .circleci/get_workflow_name.py
Labels: cla: yes

#43 chore: make samples depend on the current version
  package-lock.json
  samples/package-lock.json
  samples/package.json
Labels: cla: no

#48 regenerate GAPIC v1p1beta1 generated code
  package-lock.json
  protos/google/cloud/speech/v1p1beta1/cloud_speech.proto
  samples/package-lock.json
  src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
  src/v1p1beta1/speech_client.js
Labels: cla: yes

#47 Remove projectId argument in samples
  CONTRIBUTORS
  README.md
  package.json
  samples/quickstart.js
Labels: cla: yes

#49 release 1.3.0
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#51 chore: workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes

#50 updating GAPIC v1p1beta1 code
  protos/google/cloud/speech/v1p1beta1/cloud_speech.proto
  src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
Labels: cla: no, cla: yes

#52 release 1.4.0
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
Labels: cla: no, cla: yes

#53 chore: one more workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes
