Repository googleapis/nodejs-speech, pull requests merged in 2019-02, with the labels that each got.

#289 feat: support audioChannelCount
  .gitignore
  protos/google/cloud/speech/v1/cloud_speech.proto
  src/v1/doc/google/cloud/speech/v1/doc_cloud_speech.js
  src/v1/speech_client.js
  src/v1p1beta1/speech_client.js
  synth.metadata
Labels: cla: yes

#290 Release @google-cloud/speech v2.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#291 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#296 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#297 docs: update contributing path in README
  README.md
Labels: cla: yes

#298 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes, kokoro:force-run

#300 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#304 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#303 build: use linkinator for docs test
  package.json
Labels: cla: yes

#302 chore: update gapic error handling
  src/v1/speech_client.js
  src/v1p1beta1/speech_client.js
  synth.metadata
Labels: cla: yes

#295 Multi-channel GA sample
  samples/recognize.js
  samples/system-test/recognize.test.js
Labels: :rotating_light:, cla: yes
