Repository googleapis/nodejs-speech, pull requests merged in 2019-05, with the labels that each got.

#340 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#339 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#341 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#345 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#346 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#347 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#344 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#348 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  src/v1/speech_client_config.json
  src/v1p1beta1/speech_client_config.json
  synth.metadata
Labels: cla: yes

#351 fix: DEADLINE_EXCEEDED is idempotent
  src/v1/speech_client_config.json
  src/v1p1beta1/speech_client_config.json
  synth.metadata
Labels: cla: yes

#352 feat: add recognition metadata
  protos/google/cloud/speech/v1/cloud_speech.proto
  src/v1/doc/google/cloud/speech/v1/doc_cloud_speech.js
  synth.metadata
Labels: cla: yes

#333 new sample for infinite streaming command line app
  samples/infiniteStreaming.js
  samples/package.json
Labels: :rotating_light:, cla: yes

#354 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#358 chore: release 3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#360 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/speech_client.js
  src/v1p1beta1/speech_client.js
  synth.metadata
Labels: cla: yes

#361 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#363 feat: add support for MP3 bitrates and hint boost
  protos/google/cloud/speech/v1p1beta1/cloud_speech.proto
  src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
  synth.metadata
Labels: cla: yes

#365 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#364 chore: release 3.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#369 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#368 chore: release 3.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#371 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#372 chore: create .repo-metadata.json
  .repo-metadata.json
Labels: cla: yes
