Repository googleapis/nodejs-speech, pull requests merged in 2020-10, with the labels that each got.

#653 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#654 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: speech, automerge: exact, cla: yes, context: full

#658 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#660 docs: modernize patterns in subset of samples
  samples/.eslintrc.yml
  samples/MicrophoneStream.js
  samples/infiniteStreaming.js
  samples/package.json
  samples/quickstart.js
  samples/recognize.v1p1beta1.js
  samples/system-test/.eslintrc.yml
  samples/system-test/MicrophoneStream.test.js
  samples/system-test/recognize.v1p1beta1.test.js
  samples/transcribeContextClasses.js
Labels: cla: yes

#661 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#662 docs: update to sample in READMEs
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#665 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full
