Repository googleapis/nodejs-speech, pull requests merged in 2020-07, with the labels that each got.

#616 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#617 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#620 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#623 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#625 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#626 build: type in .gittatribute, missing closing paren in publish script, delete template for Node 8 tests, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#629 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#627 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: cla: yes

#630 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#632 build: config for new reference docs
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
