Repository googleapis/nodejs-speech, pull requests merged in 2020-09, with the labels that each got.

#640 chore: run CI on Node.js 12, fix GCS file location
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/lint.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  system-test/speech_system_test.js
  system-test/speech_system_test_v1.js
  system-test/speech_system_test_v1p1beta1.js
  system-test/speech_typescript_system_test.ts
  system-test/speech_typescript_system_test_v1.ts
  system-test/speech_typescript_system_test_v1p1beta1.ts
Labels: cla: yes

#636 build: use gapic-generator-typescript v1.0.7.
  src/v1/speech_client.ts
  src/v1p1beta1/speech_client.ts
  synth.metadata
Labels: api: speech, cla: yes, context: full

#635 build: credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: api: speech, cla: yes, context: full

#611 fix(samples): end stream before destroying it
  samples/infiniteStreaming.js
Labels: api: speech, cla: yes

#642 build: run synthtool for publish configs
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#644 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#648 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#650 samples: updated comments on recognize.js to reflect time limitations…
  samples/recognize.js
Labels: api: speech, cla: yes, samples
