Repository googleapis/nodejs-speech, pull requests merged in 2020-05, with the labels that each got.

#590 feat: check status of long running operation by its name
  protos/protos.js
  src/v1/speech_client.ts
  src/v1p1beta1/speech_client.ts
  synth.metadata
  test/gapic_speech_v1.ts
  test/gapic_speech_v1p1beta1.ts
Labels: automerge, cla: yes

#591 chore: linting rules
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#593 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#597 fix(samples): use writable stream
  samples/infiniteStreaming.js
Labels: cla: yes
