Repository googleapis/nodejs-speech, pull requests merged in 2021-06, with the labels that each got.

#757 samples: adds export to GCS sample
  .gitignore
  .vscode/launch.json
  README.md
  linkinator.config.json
  samples/README.md
  samples/export-to-storage.v1p1beta1.js
  samples/system-test/export-to-storage.v1p1beta1.test.js
Labels: api: speech, cla: yes, samples

#761 samples: update sample to lro
  samples/export-to-storage.v1p1beta1.js
Labels: api: speech, cla: yes, samples

#763 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: speech, automerge, cla: yes

#743 chore: solves resource id issues
  samples/system-test/modelAdaptation.test.js
Labels: api: speech, cla: yes

#772 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: speech, automerge, cla: yes
