Repository googleapis/nodejs-speech, pull requests merged in 2021-05, with the labels that each got.

#672 docs: add additional context to samples
  samples/transcribeContextClasses.js
Labels: api: speech, cla: yes, owlbot:run, samples

#740 fix(deps): require google-gax v2.12.0
  package.json
  samples/README.md
Labels: api: speech, automerge, cla: yes

#752 test: cleanUp should be awaited
  samples/system-test/betaFeatures.test.js
  samples/system-test/modelAdaptation.test.js
Labels: api: speech, cla: yes

#749 chore: changed assert output to check constant values
  samples/system-test/betaFeatures.test.js
Labels: api: speech, automerge, cla: yes
