Repository googleapis/nodejs-speech, pull requests merged in 2021-01, with the labels that each got.

#690 chore: update license headers
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1/index.ts
  src/v1/speech_client.ts
  src/v1p1beta1/index.ts
  src/v1p1beta1/speech_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_speech_v1.ts
  test/gapic_speech_v1p1beta1.ts
Labels: api: speech, cla: yes, context: none

#683 refactor: uses gcs remote
  samples/system-test/profanityFilter.test.js
Labels: api: speech, cla: yes

#689 docs: update CONTRIBUTING directions
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: partial

#695 refactor: move build cop to flaky bot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: speech, cla: yes, context: partial
